#! /bin/sh

if [ ! -e bin ]
then
  mkdir bin
fi

javac -d bin src/test/*.java

cd bin
jar cvf ../securitymanager.jar test/SelectiveSecurityManager*.class test/Test*.class test/ToggleSecurityManagerPermission.class
jar cvf ../untrusted.jar test/UntrustedCode.class
cd ..
